# -*- coding: utf-8 -*-
"""TP2_IMG.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZzwzpCy9xUfACXuEoWOHn2CqQ_qLLjm4
"""

import cv2
from matplotlib import pyplot as plt
import numpy as np

img = cv2.imread("monedas.jpg")
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img_gray = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2GRAY)

plt.imshow(img_gray, cmap="gray")

plt.show()

f_blur = cv2.GaussianBlur(img_gray, ksize=(3, 3), sigmaX=2)
edges = cv2.Canny(f_blur, 10, 200)

plt.imshow(edges, cmap="gray")

kernel = np.array([[0,1,0],[1,1,1],[0,1,0]],np.uint8)
Fd = cv2.dilate(edges, kernel, iterations=10)
plt.imshow(Fd, cmap="gray")

B = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5,5))
Aop = cv2.morphologyEx(Fd, cv2.MORPH_OPEN, B)

B = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5,5))
Aclau = cv2.morphologyEx(Fd, cv2.MORPH_CLOSE, B)
plt.imshow(Aclau
           , cmap='gray')
·floodFill

tino, _ = cv2.threshold(img_gray, 30, 255, cv2.THRESH_BINARY)
plt.imshow(_, cmap='gray')

cv2.hole